# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Firebase CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Deploy to Firebase
      # run: firebase deploy --only hosting --project cicd-github-react-65cb5
      uses: w9jds/firebase-action@v2.2.2
      # with:
      #   args: deploy --only hosting
     env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
    run: |
      echo "${FIREBASE_TOKEN}" > $HOME/firebase-service-account.json
      firebase deploy \
        --only hosting \
        --project cicd-github-react-65cb5 \
        --token "$(firebase login:ci --cred $HOME/firebase-service-account.json)"
